# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('channels.json', '.'), 
        ('keywords.json', '.'), 
        ('Р24 (1).png', '.'),
        ('requirements.txt', '.'),
        ('LICENSE', '.'),
        ('README.md', '.')
    ],
    hiddenimports=[
        'schedule',
        'apscheduler',
        'apscheduler.schedulers.background',
        'apscheduler.triggers.cron',
        'telegram',
        'telegram.ext',
        'PIL',
        'PIL.Image',
        'cv2',
        'numpy',
        'pandas',
        'openpyxl',
        'easyocr',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'asyncio',
        'threading',
        'logging',
        'os',
        'sys',
        'datetime',
        'time',
        'json',
        'csv',
        'shutil',
        'io',
        'psutil',
        'config_manager'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TV_Running_Lines_Monitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
